name: Build Rocket.Chat Android APK

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Checkout and Setup Node
        uses: ./.github/actions/setup-node

      - name: Build Android
        uses: ./.github/actions/build-android